//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> SuburbID { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual City City { get; set; }
        public virtual Province Province { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual Country Country { get; set; }
    }
}
