//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NdoNandiDBEntities : DbContext
    {
        public NdoNandiDBEntities()
            : base("name=NdoNandiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Allergen> Allergens { get; set; }
        public virtual DbSet<BlogEntry> BlogEntries { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<HairCondition> HairConditions { get; set; }
        public virtual DbSet<HairDensity> HairDensities { get; set; }
        public virtual DbSet<HairLength> HairLengths { get; set; }
        public virtual DbSet<InventoryItem> InventoryItems { get; set; }
        public virtual DbSet<InventoryItemType> InventoryItemTypes { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Suburb> Suburbs { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
